export default {
  happy: {
    acousticness: 0.2,
    danceability: 0.8,
    energy: 0.9,
    instrumentalness: 0.0,
    liveness: 0.3,
    loudness: -4,
    mode: 1,
    speechiness: 0.05,
    tempo: 120,
    valence: 0.95,
//    popularity: 80
  },
  sad: {
    acousticness: 0.6,
    danceability: 0.3,
    energy: 0.2,
    instrumentalness: 0.1,
    liveness: 0.2,
    loudness: -12,
    mode: 0,
    speechiness: 0.05,
    tempo: 70,
    valence: 0.1,
//    popularity: 60
  },
  energetic: {
    acousticness: 0.1,
    danceability: 0.85,
    energy: 1.0,
    instrumentalness: 0.0,
    liveness: 0.4,
    loudness: 0,
    mode: 1,
    speechiness: 0.08,
    tempo: 140,
    valence: 0.8,
//    popularity: 75
  },
  relaxed: {
    acousticness: 0.7,
    danceability: 0.5,
    energy: 0.3,
    instrumentalness: 0.3,
    liveness: 0.2,
    loudness: -10,
    mode: 1,
    speechiness: 0.04,
    tempo: 80,
    valence: 0.6,
//    popularity: 65
  },
  romantic: {
    acousticness: 0.8,
    danceability: 0.6,
    energy: 0.4,
    instrumentalness: 0.1,
    liveness: 0.25,
    loudness: -8,
    mode: 1,
    speechiness: 0.03,
    tempo: 90,
    valence: 0.75,
//    popularity: 75
  },
  aggressive: {
    acousticness: 0.05,
    danceability: 0.6,
    energy: 0.95,
    instrumentalness: 0.0,
    liveness: 0.35,
    loudness: 1,
    mode: 0,
    speechiness: 0.15,
    tempo: 150,
    valence: 0.3,
//    popularity: 55
  },
  chill: {
    acousticness: 0.6,
    danceability: 0.7,
    energy: 0.4,
    instrumentalness: 0.4,
    liveness: 0.15,
    loudness: -9,
    mode: 1,
    speechiness: 0.05,
    tempo: 85,
    valence: 0.5,
//    popularity: 65
  },
  party: {
    acousticness: 0.1,
    danceability: 0.95,
    energy: 0.9,
    instrumentalness: 0.0,
    liveness: 0.5,
    loudness: -2,
    mode: 1,
    speechiness: 0.12,
    tempo: 128,
    valence: 0.85,
//    popularity: 90
  },
  melancholy: {
    acousticness: 0.75,
    danceability: 0.4,
    energy: 0.2,
    instrumentalness: 0.2,
    liveness: 0.1,
    loudness: -15,
    mode: 0,
    speechiness: 0.04,
    tempo: 60,
    valence: 0.2,
//    popularity: 50
  },
  epic: {
    acousticness: 0.2,
    danceability: 0.5,
    energy: 0.95,
    instrumentalness: 0.6,
    liveness: 0.4,
    loudness: -1,
    mode: 1,
    speechiness: 0.02,
    tempo: 130,
    valence: 0.7,
//    popularity: 70
  }
};